### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [CreeperHost/StevesCarts2#13]
```
Minecraft v1.19.2
Forge v43.2.7
Steve's Carts v1.1.0
Poly Lib b1900.0.2-build.73
```

After installing in the server, it crashes the server during load.
[Crash Report](https://gist.github.com/WenXin20/24ad4029b0789312ad2866acdc0a8e46#file-steves_carts_server_crash-txt-L35)

**Comment by gigabit101** [comment]
Fixed in 1.1.1
