### ISSUE TITLE
Support for other loaders

### ISSUE THREAD

**Issue by VanCock** [CreeperHost/StevesCarts2#16]
It's really amazing that Steve's Carts 2 is still being worked on, it's really amazing mod with loads of possibilities and customisation, but I was wondering if fabric is something you're planning, yes I know modding isn't the easiest task, that's why I would totally understand if the answer is no, I just wanted to be sure for certain,
Cheers.  :)

**Comment by gigabit101** [comment]
There are currently no plans for us to port this to fabric, The mod is still being worked on for NeoForge and is currently on the 1.20.1 version of ForgeCraft for testing
