### ISSUE TITLE
Height Detector not showing levels

### ISSUE THREAD

**Issue by Shadowner83** [CreeperHost/StevesCarts2#2]
I built a train for mining but the Height sensor is not showing the height level. 
This makes the train just go mining downwards instead of moving forward and then going down a level.

For reference I used the same setup as Chosen Architects setup here: https://www.youtube.com/watch?v=_zqn4uqJK98&list=PL_ipI8CnaNIYn9sS5qOHkFHEfh83N09EA&index=7&t=707s

I use the FTB Ultimate Anniversary modpack version 1.1.0

**Comment by gigabit101** [comment]
Fixed in 1.1.0
