### ISSUE TITLE
Neoforge 1.20.4 Assembled cart renders oddly in hand

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/StevesCarts2#26]
After assembling your cart when you pick it up the item render is very broken.
![image](https://github.com/CreeperHost/StevesCarts2/assets/9200909/dd5e72b9-a77e-4855-819f-833764c88310)
![image](https://github.com/CreeperHost/StevesCarts2/assets/9200909/de4b34cb-4377-41a1-82ab-5a42cca6bcd0)
![image](https://github.com/CreeperHost/StevesCarts2/assets/9200909/0df78b57-7056-4395-8ace-5ecc4a5c80e5)

It looks fine when its placed in world though

**Comment by brandon3055** [comment]
Unable to reproduce with latest NeoForge, StevesCarts, PolyLib and Architectury (no other mods)

![](https://ss.brandon3055.com/29d2c)
![](https://ss.brandon3055.com/3bb15)

This may be a result of a specific mod combination. 
Ideally, we would need to know the minim set of mods required to reproduce this issue.
