### ISSUE TITLE
Neoforge 1.20.4 Engine priorities reset on server restart

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/StevesCarts2#27]
Seems like the engine priorities arent saving or loading properly across server restarts. 
Steps to reproduce:

Install a solar and coal engine on a cart, assemble, change the priorities. Restart and the priorities are back to default.

**Comment by Saereth** [comment]
This seems to be more than just engine priorities, things like information displays loose their selected displays etc on restart as well.

**Comment by brandon3055** [comment]
This is actually a synchronisation issue. The values are saved, but not properly synced to the client when the cart is loaded.
This should be resolved in the next release.

**Comment by Saereth** [comment]
does look like this is resolved now, cool!
