### ISSUE TITLE
[1.19.2] Crash when changing parts of the cart in the Cargo Manager

### ISSUE THREAD

**Issue by edukny94** [CreeperHost/StevesCarts2#30]
Tried to change the "Manager" on the blue box and got a crash after swapping modes.

![image](https://github.com/CreeperHost/StevesCarts2/assets/134519682/154b0a9f-c9b8-4e3c-8c2e-a7c2c1bd761f)

Crash log.

[crash-2024-06-03_04.22.47-server.txt](https://github.com/user-attachments/files/15528139/crash-2024-06-03_04.22.47-server.txt)

**Comment by gigabit101** [comment]
should already be fixed, Please re-open if it happens again

**Comment by edukny94** [comment]
Is is possible to get this update for 1.19.2? Is the version which I had the bug and the update is for 1.20 :(

**Comment by edukny94** [comment]
> Quote reply

Is is possible to get this update for 1.19.2? Is the version which I had the bug and the update is for 1.20 :(
