### ISSUE TITLE
1.19.2 v1.1.2 Liquid Manager does not interface with Create, XNet, Mekanism, Thermal Dynamics pipes

### ISSUE THREAD

**Issue by Masonatorr** [CreeperHost/StevesCarts2#35]
![image](https://github.com/CreeperHost/StevesCarts2/assets/42453670/4aa8bb72-c584-427e-9d56-559c6a5cf1a3)
![image](https://github.com/CreeperHost/StevesCarts2/assets/42453670/ea2cad6e-93d1-41af-86d9-59ec7f909e2e)
None of the fluid distributing blocks I have tried so far are successful in interfacing with the Liquid Manager, so I am forced to use a system of item pipes and hoppers (item distributing blocks also do not interface) to fill the tanks using buckets, which I have unfortunately now realized won't work for fueling the cart's Thermal Engine since it also requires water to be supplied.

Edit: Tried using the External Distributor, it does not connect to fluid pipes but it does connect to item pipes. But unless there's some undocumented witchcraft I have to perform, it cannot transfer fluids or fluid buckets into the Liquid Manager.

**Comment by gigabit101** [comment]
Place a Distributor block under the manager to control automatic insert and extract, This allows you to configure inserting and removing items/fluids per side

**Comment by Masonatorr** [comment]
> Place a Distributor block under the manager to control automatic insert and extract, This allows you to configure inserting and removing items/fluids per side

External Distributor still does not connect to these pipes, only to item pipes.
![image](https://github.com/CreeperHost/StevesCarts2/assets/42453670/de9e9220-9626-4279-9b46-8ad1e7916bc1)

**Comment by gigabit101** [comment]
It won't until you configure the sides and there is a cargo/fluid manager above it

**Comment by Masonatorr** [comment]
Ah I see, didnt know that since there isnt any up-to-date wiki on this stuff. Works just fine, sorry for the false report

**Comment by gigabit101** [comment]
no problem, happy to see people playing with the mod :D

**Comment by Masonatorr** [comment]
yeah I've been using steve's carts for ages so I'm glad to see there's a modern port of it :3 thank you for porting the mod! though I do miss the chunk loader module, had to install a separate mod for a chunk loader cart

**Comment by gigabit101** [comment]
I did add it back but it's in 1.20.4+

**Comment by Masonatorr** [comment]
ahhh I see, would it be possible to add it to 1.19?
(also xnet still doesnt seem to work with the external distributor but it could very well be user error, I know very little about the mod so I'm just going off of it not visually connecting to the distributor like it does with other fluid blocks)

**Comment by gigabit101** [comment]
probably not any time soon as now that Minecraft 1.21 has been released my focus is getting everything update to that

**Comment by Masonatorr** [comment]
unfortunate but fair
