### ISSUE TITLE
1.19.2 v1.1.2 Coal Engine slots accept lava buckets and will use lava as fuel

### ISSUE THREAD

**Issue by Masonatorr** [CreeperHost/StevesCarts2#36]
Not sure if this is intentional or not but it partially defeats the purpose of the Thermal Engine
![image](https://github.com/CreeperHost/StevesCarts2/assets/42453670/dd59981b-8eae-45da-a649-cd469b237d08)

**Comment by gigabit101** [comment]
Lava engine takes the fluid version, lava buckets are an acceptable fuel item just like a furnace

**Comment by Masonatorr** [comment]
Makes sense, but the name doesn't really imply that it can use lava. Maybe "Furnace Engine" or something would be better if it accepts furnace fuel

**Comment by gigabit101** [comment]
Its a port of the old mod so the name is what it was before, It might be something we can look into changing but I don't really like making changes to base mod if it can be avoided
