### ISSUE TITLE
Can't hopper into the cart assembler

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/StevesCarts2#40]
You can't hopper/pipe coal into the cart assembler currently.

neoforge 1.20.4 20.4.237
polylib-2004.0.3-build.155-neoforge.jar
stevescarts-1.20.4-1.2.6-neoforge.jar

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5403

**Comment by gigabit101** [comment]
Correct, Can add this as a config option though

**Comment by gigabit101** [comment]
Added in 1.2.7
