### ISSUE TITLE
[Bug] [Minor] Lang issue

### ISSUE THREAD

**Issue by issue14** [CreeperHost/StevesCarts2#41]
Version 1.2.7

There are inaccuracies in the en_us.json on lines 422 and 520:

422, "item.stevescarts.glass_o'magic": "Glass o'Magic", should look like "item.stevescarts.glass_o_magic": "Glass o'Magic",

520, "item.stevescarts.tri-torch": "Tri-torch", should look like "item.stevescarts.tri_torch": "Tri-torch",

**Comment by gigabit101** [comment]
fixed in 1.2.12
