### ISSUE TITLE
1,21 cart assamble doesnt save the items on exit the world

### ISSUE THREAD

**Issue by castilio20** [CreeperHost/StevesCarts2#42]
Seems like the cart assamble doesnt save the items that are in the gui if you exit the world and enter again
![2024-08-23_10 58 45](https://github.com/user-attachments/assets/9938f6ec-db28-4898-baca-dc840d21de4d)
![2024-08-23_10 59 00](https://github.com/user-attachments/assets/df84c125-4277-48f5-8987-47a3b34a29a2)

**Comment by castilio20** [comment]
a similar issue hapend where the end result disapeared could it be bc of this issue somehow or chunkloading issue voiding the item?(i didnt exit the world but just gone exploring until the cart was ready
)

**Comment by gigabit101** [comment]
fixed in latest build
