### ISSUE TITLE
Tank Locking in cart

### ISSUE THREAD

**Issue by bookerthegeek** [CreeperHost/StevesCarts2#48]
## Heyo

Version: 1.21-1.2.11
Pack: ATM10

### Issue:
Locking a tank to a specific liquid/fluid, while saying it is locked, will still allow any liquid/fluid into that locked tank.

### Steps to reproduce:
 - Create a cart with one or more tanks.
 - Set one tank to water.
 - Remove all fluid from that tank with the liquid manager
 - Add lava in with a liquid manager.
 - See lava go into the empty tank locked to water.

**Comment by gigabit101** [comment]
fixed in 1.2.12
